lava_server/urls.py
# Copyright (C) 2010-2018 Linaro Limited
#
# Author: Zygmunt Krynicki <zygmunt.krynicki@linaro.org>
#
# SPDX-License-Identifier: GPL-2.0-or-later

from django.conf import settings
from django.contrib import admin
from django.urls import include, path, register_converter
from django.views.generic import TemplateView
from django.views.i18n import JavaScriptCatalog

from lava_common.converters import JobIdConverter
from lava_results_app.api import ResultsAPI
from lava_scheduler_app.api import SchedulerAPI
from lava_scheduler_app.api.aliases import SchedulerAliasesAPI
from lava_scheduler_app.api.device_types import (
    SchedulerDeviceTypesAliasesAPI,
    SchedulerDeviceTypesAPI,
)
from lava_scheduler_app.api.devices import SchedulerDevicesAPI, SchedulerDevicesTagsAPI
from lava_scheduler_app.api.jobs import SchedulerJobsAPI
from lava_scheduler_app.api.tags import SchedulerTagsAPI
from lava_scheduler_app.api.workers import SchedulerWorkersAPI
from lava_server.api import LavaMapper
from lava_server.api.groups import GroupsAPI, GroupsPermissionsAPI
from lava_server.api.users import UsersAPI, UsersGroupsAPI, UsersPermissionsAPI
from lava_server.views import (
    delete_remote_auth,
    healthz,
    index,
    me,
    prometheus,
    update_irc_settings,
    update_remote_auth,
    update_table_length_setting,
)
from linaro_django_xmlrpc.views import handler as linaro_django_xmlrpc_views_handler
from linaro_django_xmlrpc.views import help as linaro_django_xmlrpc_views_help

handler403 = "lava_server.views.permission_error"
handler500 = "lava_server.views.server_error"

# Enable admin stuff
admin.autodiscover()

# Create the XMLRPC mapper
mapper = LavaMapper()
mapper.register_introspection_methods()
mapper.register(ResultsAPI, "results")
mapper.register(SchedulerAPI, "scheduler")
mapper.register(SchedulerAliasesAPI, "scheduler.aliases")
mapper.register(SchedulerDevicesAPI, "scheduler.devices")
mapper.register(SchedulerDevicesTagsAPI, "scheduler.devices.tags")
mapper.register(SchedulerDeviceTypesAPI, "scheduler.device_types")
mapper.register(SchedulerDeviceTypesAliasesAPI, "scheduler.device_types.aliases")
mapper.register(SchedulerJobsAPI, "scheduler.jobs")
mapper.register(SchedulerTagsAPI, "scheduler.tags")
mapper.register(SchedulerWorkersAPI, "scheduler.workers")
mapper.register(GroupsAPI, "auth.groups")
mapper.register(GroupsPermissionsAPI, "auth.groups.perms")
mapper.register(UsersAPI, "auth.users")
mapper.register(UsersGroupsAPI, "auth.users.groups")
mapper.register(UsersPermissionsAPI, "auth.users.perms")

register_converter(JobIdConverter, "job_id")

# Auth backends
auth_urls = [
    path(
        "accounts/",
        include("django.contrib.auth.urls"),
    )
]

if (
    "allauth.account.auth_backends.AuthenticationBackend"
    in settings.AUTHENTICATION_BACKENDS
):
    auth_urls.append(
        path(
            "accounts/",
            include("allauth.urls"),
        )
    )

if settings.OIDC_ENABLED:
    auth_urls.append(
        path(
            "oidc/",
            include("mozilla_django_oidc.urls"),
        )
    )

# Root URL patterns
urlpatterns = [
    path(
        "robots.txt",
        TemplateView.as_view(template_name="robots.txt"),
        name="robots",
    ),
    path(
        settings.MOUNT_POINT,
        include(
            [
                path("", index, name="lava.home"),
                path(
                    "v1/healthz/",
                    healthz,
                    name="lava.healthz",
                ),
                path(
                    "v1/prometheus/",
                    prometheus,
                    name="lava.prometheus",
                ),
                path(
                    "me/",
                    me,
                    name="lava.me",
                ),
                path(
                    "update-irc-settings/",
                    update_irc_settings,
                    name="lava.update_irc_settings",
                ),
                path(
                    "update-remote-auth/",
                    update_remote_auth,
                    name="lava.update_remote_auth",
                ),
                path(
                    "delete-remote-auth/<int:pk>/",
                    delete_remote_auth,
                    name="lava.delete_remote_auth",
                ),
                path(
                    "update-table-length-setting/",
                    update_table_length_setting,
                    name="lava.update_table_length_setting",
                ),
                *auth_urls,
                path(
                    "admin/",
                    admin.site.urls,
                ),
                # RPC endpoints
                path(
                    "RPC2/",
                    linaro_django_xmlrpc_views_handler,
                    name="lava.api_handler",
                    kwargs={"mapper": mapper, "help_view": "lava.api_help"},
                ),
                path(
                    "RPC2",
                    linaro_django_xmlrpc_views_handler,
                    kwargs={"mapper": mapper, "help_view": "lava.api_help"},
                ),
                path(
                    "api/help/",
                    linaro_django_xmlrpc_views_help,
                    name="lava.api_help",
                    kwargs={"mapper": mapper},
                ),
                path(
                    "api/",
                    include("linaro_django_xmlrpc.urls"),
                ),
                path(
                    "results/",
                    include("lava_results_app.urls"),
                ),
                path(
                    "scheduler/",
                    include("lava_scheduler_app.urls"),
                ),
                # REST API
                path(
                    "api/",
                    include("lava_rest_app.urls"),
                ),
            ]
        ),
    ),
    path("admin/jsi18n", JavaScriptCatalog.as_view()),
]


if settings.USE_DEBUG_TOOLBAR:
    import debug_toolbar

    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

lava_results_app/models.py
# Copyright (C) 2015-2019 Linaro Limited
#
# Author: Stevan Radakovic <stevan.radakovic@linaro.org>
#
# SPDX-License-Identifier: GPL-2.0-or-later

"""
Database models of the LAVA Results

    results/<job-ID>/<lava-suite-name>/<lava-test-set>/<lava-test-case>
    results/<job-ID>/<lava-suite-name>/<lava-test-case>

TestSuite is based on the test definition
TestSet can be enabled within a test definition run step
TestCase is a single lava-test-case record or Action result.
"""

import contextlib
import logging
from datetime import timedelta
from urllib.parse import quote

import yaml
from django.conf import settings
from django.contrib.auth.models import Group, User
from django.contrib.contenttypes import fields
from django.contrib.contenttypes.models import ContentType
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import connection, models, transaction
from django.db.models import Count, Lookup, Q
from django.db.models.fields import Field
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from psycopg2.extensions import quote_ident

from lava_common.decorators import nottest
from lava_common.yaml import yaml_safe_load
from lava_results_app.utils import help_max_length
from lava_scheduler_app.managers import (
    RestrictedTestCaseQuerySet,
    RestrictedTestJobQuerySet,
    RestrictedTestSuiteQuerySet,
)
from lava_scheduler_app.models import Device, TestJob
from lava_server.managers import MaterializedView


class InvalidConditionsError(Exception):
    """Raise when querying by URL has incorrect condition arguments."""


class InvalidContentTypeError(Exception):
    """Raise when querying by URL content type (table name)."""


class QueryUpdatedError(Exception):
    """Error raised if query is updating or recently updated."""


class RefreshLiveQueryError(Exception):
    """Error raised if refreshing the live query is attempted."""


class Queryable:
    """All Queryable objects should inherit this."""

    def get_passfail_results(self):
        raise NotImplementedError("Should have implemented this")

    def get_measurement_results(self):
        raise NotImplementedError("Should have implemented this")

    def get_attribute_results(self, attributes):
        raise NotImplementedError("Should have implemented this")

    def get_end_datetime(self):
        raise NotImplementedError("Should have implemented this")

    def get_xaxis_attribute(self):
        raise NotImplementedError("Should have implemented this")


@Field.register_lookup
class NotEqual(Lookup):
    # Class for __ne field lookup.
    lookup_name = "ne"

    def as_sql(self, compiler, connection):
        lhs, lhs_params = self.process_lhs(compiler, connection)
        rhs, rhs_params = self.process_rhs(compiler, connection)
        params = lhs_params + rhs_params
        return "%s <> %s" % (lhs, rhs), params


class QueryMaterializedView(MaterializedView):
    class Meta:
        abstract = True

    QUERY_VIEW_PREFIX = "query_"

    @classmethod
    def create(cls, query):
        # Check if view for this query exists.
        if cls.view_exists(query.id):
            return

        with connection.cursor() as cursor:
            sql, params = Query.get_queryset(
                query.content_type, query.querycondition_set.all(), query.limit
            ).query.sql_with_params()

            query_id_str = f"{cls.QUERY_VIEW_PREFIX}{query.id}"
            # Must be quoted separately as otherwise
            # will be quoted with single quotes making
            # it incompatible with table_name identifier
            query_id_str_quoted = quote_ident(query_id_str, cursor.cursor)
            # TODO: handle potential exceptions here. what to do if query
            # view is not created? - new field update_status?
            cursor.execute(
                f"CREATE MATERIALIZED VIEW {query_id_str_quoted} AS {sql}",
                params,
            )

    @classmethod
    def refresh(cls, query_id):
        with connection.cursor() as cursor:
            query_id_str = f"{cls.QUERY_VIEW_PREFIX}{query_id}"
            # Must be quoted separately as otherwise
            # will be quoted with single quotes making
            # it incompatible with table_name identifier
            query_id_str_quoted = quote_ident(query_id_str, cursor.cursor)
            cursor.execute(
                f"REFRESH MATERIALIZED VIEW {query_id_str_quoted}",
            )

    @classmethod
    def drop(cls, query_id):
        with connection.cursor() as cursor:
            query_id_str = f"{cls.QUERY_VIEW_PREFIX}{query_id}"
            # Must be quoted separately as otherwise
            # will be quoted with single quotes making
            # it incompatible with table_name identifier
            query_id_str_quoted = quote_ident(query_id_str, cursor.cursor)
            cursor.execute(
                f"DROP MATERIALIZED VIEW IF EXISTS {query_id_str_quoted}",
            )

    @classmethod
    def view_exists(cls, query_id):
        with connection.cursor() as cursor:
            query_id_str = f"{cls.QUERY_VIEW_PREFIX}{query_id}"
            cursor.execute(
                "SELECT EXISTS(SELECT 1 FROM pg_class WHERE relname=%s)",
                (query_id_str,),
            )
            return cursor.fetchone()[0]

    def get_queryset(self):
        return QueryMaterializedView.objects.all()


@nottest
class TestSuite(models.Model, Queryable):
    """
    Result suite of a pipeline job.
    Top level grouping of results from a job.
    Directly linked to a single TestJob, the job can have multiple TestSets.
    """

    class Meta:
        constraints = (
            models.UniqueConstraint(
                fields=("job", "name"), name="lava_results_app_testsuite_job_name_uniq"
            ),
        )

    objects = models.Manager.from_queryset(RestrictedTestSuiteQuerySet)()

    job = models.ForeignKey(
        TestJob,
        on_delete=models.CASCADE,
        db_index=False,  # UniqueConstraint defined in Meta
    )
    name = models.CharField(
        verbose_name="Suite name", blank=True, null=True, default=None, max_length=200
    )

    def testcase_count(self, value=None):
        if not hasattr(self, "_testcase_count"):
            res = self.testcase_set.values("result")
            res = res.aggregate(
                PASS=Count(
                    "pk",
                    filter=Q(result=TestCase.RESULT_PASS),
                ),
                FAIL=Count(
                    "pk",
                    filter=Q(result=TestCase.RESULT_FAIL),
                ),
                SKIP=Count(
                    "pk",
                    filter=Q(result=TestCase.RESULT_SKIP),
                ),
                UNKNOWN=Count(
                    "pk",
                    filter=Q(result=TestCase.RESULT_UNKNOWN),
                ),
            )
            self._testcase_count = {k.lower(): (v or 0) for (k, v) in res.items()}

        if value is None:
            return sum([v for (k, v) in self._testcase_count.items()])
        return self._testcase_count[value]

    def get_passfail_results(self):
        # Get pass fail results per lava_results_app.testsuite.
        return {
            self.name: {
                "pass": self.testcase_count("pass"),
                "fail": self.testcase_count("fail"),
                "skip": self.testcase_count("skip"),
                "unknown": self.testcase_count("unknown"),
            }
        }

    def get_measurement_results(self):
        # Get measurement values per lava_results_app.testcase.
        results = {}

        for testcase in self.testcase_set.all():
            results[testcase.name] = {}
            results[testcase.name]["measurement"] = testcase.measurement
            results[testcase.name]["fail"] = testcase.result != TestCase.RESULT_PASS

        return results

    def get_attribute_results(self, attributes):
        # Get attribute values per lava_results_app.testsuite.
        results = {}
        attributes = [x.strip() for x in attributes.split(",")]
        for testcase in self.testcase_set.all():
            if testcase.action_metadata:
                for key in testcase.action_metadata:
                    if key in attributes and key not in results:
                        # Use only the metadata from the first testcase atm.
                        results[key] = {}
                        results[key]["fail"] = testcase.result != TestCase.RESULT_PASS
                        try:
                            results[key]["value"] = float(testcase.action_metadata[key])
                        except ValueError:
                            # Ignore non-float metadata.
                            del results[key]

        return results

    def get_end_datetime(self):
        return self.job.end_time

    def get_xaxis_attribute(self, xaxis_attribute=None):
        return self.job.get_xaxis_attribute(xaxis_attribute)

    def get_absolute_url(self):
        """
        Web friendly name for the test suite
        """
        return reverse("lava.results.suite", args=[self.job.id, self.name])

    def __str__(self):
        """
        Human friendly name for the test suite
        """
        return _("Test Suite {0}/{1}").format(self.job.id, self.name)


@nottest
class TestSet(models.Model):
    """
    Sets collate result cases under an arbitrary text label.
    Not all cases have a TestSet
    """

    class Meta:
        constraints = (
            models.UniqueConstraint(
                fields=("suite", "name"),
                name="lava_results_app_testset_name_suite_uniq",
            ),
        )

    id = models.AutoField(primary_key=True)

    name = models.CharField(
        verbose_name="Suite name", blank=True, null=True, default=None, max_length=200
    )

lava_server/templates/_similar_jobs.html
<!-- Modal HTML -->
<div id="similar_jobs_modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title">Find similar test jobs</h3>
        <p>
          Add query criteria to identify other test jobs similar to this one, e.g. by submitter, actual_device, user, status or metadata generated by this test job.
        </p>
        <p>
          Hint: Please take a look at the metadata of the test job results to find out more about the available metadata fields.
        </p>
        <p>
          Hint: Start typing to search for the available fields depending on the entity.<br>Available fields will appear in a list below.
        </p>
      </div>
      <div class="modal-body">
	<div id="similar_jobs_errors" class="errorlist" style="color: red;"></div>
	<form id="similar_jobs_form" class="well" method="post" action="{% url 'lava.scheduler.job.similar_jobs' job.pk %}">
          <input id="id_condition_choices" type="hidden" value="{{ condition_choices }}"/>
          <input id="id_available_content_types" type="hidden" value="{{ available_content_types }}"/>
          <div class="row">
            <div class="col-xs-4">
              <strong>Match entity</strong>
            </div>
            <div class="col-xs-4">
              <strong>Match field</strong>
            </div>
          </div>
          <br>
          <div id="options_container">
	    {% csrf_token %}
          </div>
          <hr/>
          <a onclick="add_option_row();" class="btn btn-sm btn-primary" href="javascript: void(0);">
            Add new option
          </a>
	</form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button id="submit_similar_jobs" type="button" class="btn btn-primary">Continue</button>
      </div>
    </div>
  </div>
</div>

lava_server/templates/lazytables.html
{% extends "tables.html" %}

{% block pagination.current %}
    <li>Page {{ table.page.number }}</li>
{% endblock pagination.current %}

{% block pagination.cardinality %}{% endblock %}

lava_server/templates/me.html
{% extends "layouts/content.html" %}
{% load i18n %}
{% load static %}

{% block content %}
<h2>Hi {% firstof user.first_name user.username %}</h2>
<div class="row">
  <div class="col-md-6">
    <h4 class="modal-header">Personal information</h4>
    <dl class="dl-horizontal">
      <dt>Full name</dt>
      <dd>{{ user.get_full_name|default:"??" }}</dd>
      <dt>Username</dt>
      <dd>{{ user.username }}</dd>
      <dt>Email</dt>
      <dd>{{ user.email|default:"??" }}</dd>
      <dt>Joined</dt>
      <dd><span title="{{ user.date_joined }}">
          {{user.date_joined|timesince }} ago</span></dd>
      <dt>Password</dt>
      <dd><a href="{% url 'password_change' %}"><span class="glyphicon glyphicon-lock"></span> Update</a></dd>
      {% if socialaccount_enabled %}
      <dt>Social accounts</dt>
      <dd><a href="{% url 'socialaccount_connections' %}"><span class="glyphicon glyphicon-link"></span> Manage connections</a></dd>
      {% endif %}
      <dt>IRC settings</dt>
      <dd>Server: {{ user.extendeduser.irc_server|default:"None" }}; Handle: {{ user.extendeduser.irc_handle|default:"None" }};<a data-toggle="modal" href="#irc_modal"> Update</a></dd>
      <dt>Default table length</dt>
      <dd>{{ user.extendeduser.table_length|default:"System default" }} <a data-toggle="modal" href="#table_length_modal">Update</a></dd>
    </dl>
  </div>

  <!-- Modal HTML -->
  <div id="irc_modal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Update IRC settings</h4>
        </div>
        <form id="irc_form" method="post" action="{% url 'lava.update_irc_settings' %}">
	  {% csrf_token %}
        <div class="modal-body well">
	  <div class="errorlist" style="color: red;"></div>
	    {{ irc_form.as_p }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <input class="btn btn-primary" type="submit" value="Save">
        </div>
        </form>

      </div>
    </div>
  </div>

  <!-- Modal HTML -->
  <div id="table_length_modal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Update table length setting</h4>
        </div>
        <form id="table_length_form" method="post" action="{% url 'lava.update_table_length_setting' %}">
	  {% csrf_token %}
        <div class="modal-body well">
	  <div class="errorlist" style="color: red;"></div>
	    {{ table_length_form.as_p }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <input class="btn btn-primary" type="submit" value="Save">
        </div>
        </form>

      </div>
    </div>
  </div>

  <div class="col-md-6">
    <h4 class="modal-header">Groups</h4>
  {% with groups=user.groups.all %}
    {% if groups %}
    <p>You are member of the following LAVA groups:</p>
    <div class="panel-group">
    {% for group in groups %}
      {% with user_set=group.user_set.all %}
        {% with users_count=user_set|length %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            {% if users_count > 1 %}
              <a data-toggle="collapse" data-parent="#accordion" href="#collapse-{{ forloop.counter }}">{{ group.name }} <span class="badge pull-right">{{ users_count|add:"-1" }}</span></a>
            {% else %}
              {{ group.name }} <span class="badge pull-right">0</span>
            {% endif %}
          </h4>
        </div>
        {% if users_count > 1 %}
        <div id="collapse-{{ forloop.counter }}" class="panel-collapse collapse">
          <div class="panel-body">
            <ul>
            {% for group_user in user_set|dictsort:"first_name"|dictsort:"last_name" %}
              {% if group_user != user %}<li>{{ group_user.get_full_name|default:group_user.username }}</li>{% endif %}
            {% endfor %}
            </ul>
          </div>
        </div>
        {% endif %}
      </div>
        {% endwith %}
      {% endwith %}
    {% endfor %}
    </div>
    {% else %}
    <p><i>You are not member of any group.</i></p>
    {% endif %}
  {% endwith %}
  </div>


</div>
<div class="row">
  <div class="col-md-6">
    <h4 class="modal-header">Personal reports</h4>
    <ul class="nav nav-pills nav-stacked">
      <li>
        <a href="{% url 'lava.scheduler.myjobs' %}">
          <span class="glyphicon glyphicon-tasks pull-right"></span> Your jobs</a>
      </li>
      <li>
        <a href="{% url 'lava.scheduler.mydevice_list' %}">
          <span class="glyphicon glyphicon-phone pull-right"></span> Your devices</a>
      </li>
      <li>
        <a href="{% url 'lava.scheduler.mydevices_health_history_log' %}">
          <span class="glyphicon glyphicon-heart pull-right"></span> Your devices health</a>
      </li>
    </ul>
  </div>

  <div class="col-md-6">
    <h4 class="modal-header">Remote artifact tokens <small><a data-toggle="modal" href="#token_modal" class="btn btn-xs btn-info empty-token-modal"><span class="glyphicon glyphicon-plus-sign"></span> Create</a></small></h4>
    {% with tokens=user.remoteartifactsauth_set.all %}
    {% if tokens %}
    <p>You have following tokens:</p>
    <div class="panel-group">
      {% for token_obj in tokens %}
      <div class="panel panel-default">
        <div class="panel-heading">
          <h4 class="panel-title">
            <a data-toggle="modal" data-id="{{ token_obj.id }}" data-name="{{ token_obj.name }}" data-token="{{ token_obj.token }}" href="#token_modal" class="open-token-modal"><span>{{ token_obj.name }}</span></a>
            <a class="btn btn-xs btn-danger pull-right" style="color: #fff" title="Delete token" href="{% url 'lava.delete_remote_auth' token_obj.id %}" data-toggle="confirm" data-title="Are you sure you want to delete this token?">
              <span class="glyphicon glyphicon-trash"></span>
            </a>
          </h4>
        </div>
      </div>
    {% endfor %}
    </div>
    {% else %}
    <p><i>You have no tokens.</i></p>
    {% endif %}
  {% endwith %}
  </div>

  <!-- Modal HTML -->
  <div id="token_modal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Add/Update token</h4>
        </div>
        <form id="token_form" method="post" action="{% url 'lava.update_remote_auth' %}">
	  {% csrf_token %}
        <div class="modal-body well">
	  <div id="token_errors" class="errorlist" style="color: red;"></div>
          <p><label for="id_name">Token name:</label> <input type="text" name="name" maxlength="100" id="id_name"><input type="hidden" name="id" id="id_id"></p>
          <p><label for="id_token">Token string:</label> <input type="text" name="token" maxlength="200" id="id_token">
          </p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <input class="btn btn-primary" type="submit" value="Save">
        </div>
        </form>

      </div>
    </div>
  </div>

</div>

{% endblock %}

{% block scripts %}
<script src="{% static 'lava_server/js/bootbox.js' %}"></script>
<script src="{% static 'lava_results_app/js/bootbox.data.toggle.js' %}"></script>
<script>
$(document).ready(function () {
    add_bootbox_data_toggle();
    $(document).on("click", ".open-token-modal", function () {
        $(".modal-body #id_id").val($(this).data('id'));
        $(".modal-body #id_name").val($(this).data('name'));
        $(".modal-body #id_token").val($(this).data('token'));
    }).on("click", ".empty-token-modal", function () {
        $(".modal-body #id_id").val("");
        $(".modal-body #id_name").val("");
        $(".modal-body #id_token").val("");
    });
});
</script>
{% endblock %}

lava_server/templates/socialaccount.html
{% load static %}
{% load account socialaccount %}

{% get_static_prefix as static_prefix %}
{% get_providers as socialaccount_providers %}

{% if socialaccount_providers %}
<div class="col-md-4">
  <h4>Social account Login</h4>
  <hr/>
  {% for provider in socialaccount_providers %}
    <p>
      <form method="post" action="/accounts/{{provider.id}}/login/">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{next}}"/>
        <button type="submit"
                title="{{provider.name}}"
                style="width: 132px"
                class="btn btn-default socialaccount_provider {{provider.id}}">
            <img src='{{static_prefix}}/lava_server/images/auth/{{provider.id}}.png'/> {{provider.name}}
        </button>
      </form>
    </p>
  {% endfor %}
</div>
{% endif %}